spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://mysql:3306/${DB_NAME}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      database: 1

file:
  access-url-base: http://localhost:8080/files/
  storage-path: /app/files/
  directories:
    member: member
    board: board